default:
    trainer: online_bc
    batch_size: 64
    time_horizon: 64
    summary_freq: 1000
    max_steps: 5.0e6
    batches_per_epoch: 10
    use_recurrent: false
    hidden_units: 128
    learning_rate: 3.0e-4
    num_layers: 2
    sequence_length: 16
    memory_size: 256
            
BoxerLearning:
    trainer: online_bc
    brain_to_imitate: ExpertHeuristic
    summary_freq: 200
    batch_size: 16
    batches_per_epoch: 5
    hidden_units: 256
    num_layers: 1
    learning_rate: 0.001